name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar imagem no Docker Hub
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${REPO_NAME}:${IMAGE_TAG}"

          docker build -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Atualizar imagem no arquivo deployment.yaml
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          cd $(basename "$GITHUB_REPOSITORY")

          sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}|" k8s/deployment.yaml

          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add k8s/deployment.yaml
          git commit -m "Atualizando imagem para $IMAGE_NAME"
          git push
